import { ArborNode } from './types';

const getPastDate = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const initialNodes: ArborNode[] = [
  {
    id: 'root-1',
    parentId: null,
    title: 'ReadWorks reach and mission',
    type: 'concept',
    content:
      'ReadWorks is a nonprofit literacy organization focused on improving reading comprehension through high-quality content, curriculum, and digital tools.',
    color: '#059fc5',
    tags: ['mission', 'impact', 'readworks'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'c-1',
    parentId: 'root-1',
    title: 'Scale snapshot',
    type: 'concept',
    content: 'This branch tracks the public facts used across the staff portal and dashboard surfaces.',
    tags: ['impact', 'facts', 'about'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'i-1',
    parentId: 'c-1',
    title: 'ReadWorks impact overview',
    type: 'image',
    imageUrl: '/readworks-impact-overview.svg',
    tags: ['impact', 'overview'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-1',
    parentId: 'c-1',
    title: 'Official scale note',
    type: 'text',
    content:
      'ReadWorks says it offers 6,000 plus texts, serves all 50 states, reaches nearly 1 million educators and 11 million students each school year, and reaches 93% of the nation\'s lowest-income K-8 schools. Those public metrics anchor the portal copy and sample planning views.',
    tags: ['impact', 'metrics', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-1',
    parentId: 'c-1',
    title: 'ReadWorks About',
    type: 'link',
    url: 'https://about.readworks.org/index.html',
    content: 'Official ReadWorks overview and impact page.',
    tags: ['about', 'official', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-1',
    parentId: 'c-1',
    title: 'Refresh homepage fact stack',
    type: 'task',
    completed: false,
    tags: ['metrics', 'homepage', 'content'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'c-2',
    parentId: 'root-1',
    title: '2026 recognition and messaging',
    type: 'concept',
    content: 'Track organization-level announcements that should surface in partner decks and internal talking points.',
    tags: ['recognition', 'partners', 'messaging'],
    updatedAt: getPastDate(3),
  },
  {
    id: 't-2',
    parentId: 'c-2',
    title: 'Top 25 nonprofit note',
    type: 'text',
    content:
      'ReadWorks published a January 23, 2026 update announcing that it was named a Top 25 global impact-certified nonprofit. The staff portal uses that post as a current proof point for partner-facing credibility.',
    tags: ['2026', 'impact', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-2',
    parentId: 'c-2',
    title: 'Top 25 global impact-certified nonprofit',
    type: 'link',
    url: 'https://about.readworks.org/readworks-is-a-top-25-global-impact-certified-nonprofit',
    content: 'Official January 23, 2026 recognition post.',
    tags: ['official', '2026', 'recognition'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-2',
    parentId: 'c-2',
    title: 'Add January 2026 recognition to partner packet',
    type: 'task',
    completed: false,
    tags: ['partners', 'deck', 'recognition'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-2',
    parentId: null,
    title: 'Core classroom programs',
    type: 'concept',
    content:
      'Public program workspace covering Article-A-Day, StepReads, Book Studies, and paired-text supports used across the portal.',
    color: '#24678d',
    tags: ['programs', 'classroom', 'curriculum'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'c-3',
    parentId: 'root-2',
    title: 'Article-A-Day and StepReads',
    type: 'concept',
    content: 'Daily routine, differentiated text access, and teacher support notes live together in this branch.',
    tags: ['article-a-day', 'stepreads', 'reading'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'i-2',
    parentId: 'c-3',
    title: 'Article-A-Day program card',
    type: 'image',
    imageUrl: '/readworks-article-a-day.svg',
    tags: ['article-a-day', 'card'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-3',
    parentId: 'c-3',
    title: 'Daily routine summary',
    type: 'text',
    content:
      'ReadWorks positions Article-A-Day as a short daily classroom routine. StepReads extends that work with differentiated reading support so teachers can keep more students in the same knowledge-building sequence.',
    tags: ['article-a-day', 'stepreads', 'summary'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-3',
    parentId: 'c-3',
    title: 'Article-A-Day',
    type: 'link',
    url: 'https://www.readworks.org/article-a-day',
    content: 'Official ReadWorks Article-A-Day page.',
    tags: ['official', 'article-a-day'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-4',
    parentId: 'c-3',
    title: 'StepReads',
    type: 'link',
    url: 'https://www.readworks.org/stepreads',
    content: 'Official ReadWorks StepReads page.',
    tags: ['official', 'stepreads'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-3',
    parentId: 'c-3',
    title: 'Refresh daily routine brief',
    type: 'task',
    completed: true,
    tags: ['article-a-day', 'teacher-support', 'done'],
    updatedAt: getPastDate(4),
  },
  {
    id: 'c-4',
    parentId: 'root-2',
    title: 'Book Studies and paired texts',
    type: 'concept',
    content: 'This branch holds deeper unit work, bilingual supports, and teacher implementation notes.',
    tags: ['book-studies', 'paired-texts', 'supports'],
    updatedAt: getPastDate(3),
  },
  {
    id: 't-4',
    parentId: 'c-4',
    title: 'Program stack note',
    type: 'text',
    content:
      'Book Studies gives teachers longer-form literacy units, while Spanish-English paired texts support bilingual classrooms and cross-language comprehension work. The portal uses both as real program anchors for sample curation and QA tasks.',
    tags: ['book-studies', 'bilingual', 'qa'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-5',
    parentId: 'c-4',
    title: 'Book Studies',
    type: 'link',
    url: 'https://www.readworks.org/book-studies',
    content: 'Official ReadWorks Book Studies page.',
    tags: ['official', 'book-studies'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'l-6',
    parentId: 'c-4',
    title: 'Spanish-English paired texts',
    type: 'link',
    url: 'https://www.readworks.org/spanish-english-paired-texts',
    content: 'Official bilingual paired-texts page.',
    tags: ['official', 'bilingual', 'paired-texts'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-4',
    parentId: 'c-4',
    title: 'QA bilingual resource landing copy',
    type: 'task',
    completed: false,
    tags: ['bilingual', 'content', 'qa'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-3',
    parentId: null,
    title: 'Webinar pipeline',
    type: 'concept',
    content:
      'Kanban-style working area for educator webinar operations tied to official ReadWorks webinars and public resource launches.',
    color: '#ef8e3b',
    tags: ['kanban', 'webinars', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'k-todo',
    parentId: 'root-3',
    title: 'To Do',
    type: 'concept',
    tags: ['status:todo'],
    updatedAt: getPastDate(3),
  },
  {
    id: 'k-inprog',
    parentId: 'root-3',
    title: 'In Progress',
    type: 'concept',
    tags: ['status:in-progress'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'k-done',
    parentId: 'root-3',
    title: 'Done',
    type: 'concept',
    tags: ['status:done'],
    updatedAt: getPastDate(4),
  },
  {
    id: 'task-5',
    parentId: 'k-todo',
    title: 'Draft March 24 joint webinar deck',
    type: 'task',
    content: 'Build moderator framing and teacher examples for the March 24, 2026 session with Read STOP Write.',
    completed: false,
    tags: ['webinars', '2026', 'deck'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-6',
    parentId: 'k-todo',
    title: 'Package partner follow-up resources',
    type: 'task',
    content: 'Bundle teacher guide links, alignments, and partner notes after the next webinar cycle.',
    completed: false,
    tags: ['partners', 'teacher-guide', 'follow-up'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'task-7',
    parentId: 'k-inprog',
    title: 'Confirm moderator notes for diverse learners session',
    type: 'task',
    content: 'Turn the February 24, 2026 diverse learners webinar framing into reusable support guidance.',
    completed: false,
    tags: ['webinars', 'support', 'diverse-learners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-8',
    parentId: 'k-done',
    title: 'Publish registration reminder copy',
    type: 'task',
    content: 'Initial webinar promotion copy is approved and archived in the portal.',
    completed: true,
    tags: ['webinars', 'copy', 'done'],
    updatedAt: getPastDate(5),
  },
  {
    id: 'root-4',
    parentId: null,
    title: 'ReadWorks public calendar 2026',
    type: 'concept',
    content: 'Public-facing dates and updates referenced by the staff portal.',
    color: '#059fc5',
    tags: ['calendar', 'public', '2026'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-1',
    parentId: 'root-4',
    title: 'Top 25 global impact-certified nonprofit post',
    type: 'event',
    content: 'Official ReadWorks recognition post published January 23, 2026.',
    startDate: '2026-01-23',
    tags: ['recognition', '2026', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-2',
    parentId: 'root-4',
    title: 'Mississippi partnership update',
    type: 'event',
    content: 'Official partnership update published February 11, 2026.',
    startDate: '2026-02-11',
    tags: ['partnerships', 'mississippi', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-3',
    parentId: 'root-4',
    title: '5 ways to boost engagement with high-quality texts',
    type: 'event',
    content: 'Official webinar listed for February 10, 2026.',
    startDate: '2026-02-10',
    tags: ['webinars', 'teachers', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-4',
    parentId: 'root-4',
    title: 'Supporting diverse learners with high-quality content',
    type: 'event',
    content: 'Official webinar listed for February 24, 2026.',
    startDate: '2026-02-24',
    tags: ['webinars', 'diverse-learners', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-5',
    parentId: 'root-4',
    title: 'Joint webinar with Read STOP Write',
    type: 'event',
    content: 'Official webinar listed for March 24, 2026.',
    startDate: '2026-03-24',
    tags: ['webinars', 'partners', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-5',
    parentId: null,
    title: 'ReadWorks resource gallery',
    type: 'concept',
    content: 'Visual cards used by the portal for current ReadWorks programs and public organization facts.',
    color: '#2f6f9b',
    tags: ['gallery', 'cards', 'design'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-1',
    parentId: 'root-5',
    title: 'Article-A-Day card',
    type: 'image',
    content: '/readworks-article-a-day.svg',
    tags: ['article-a-day', 'programs'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-2',
    parentId: 'root-5',
    title: 'Webinars 2026 card',
    type: 'image',
    content: '/readworks-webinars-2026.svg',
    tags: ['webinars', '2026'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-3',
    parentId: 'root-5',
    title: 'Partnerships card',
    type: 'image',
    content: '/readworks-partnerships-map.svg',
    tags: ['partnerships', 'states'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-4',
    parentId: 'root-5',
    title: 'Impact overview card',
    type: 'image',
    content: '/readworks-impact-overview.svg',
    tags: ['impact', 'metrics'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-6',
    parentId: null,
    title: 'Partnerships and supports',
    type: 'concept',
    content: 'Reference table for state partnerships, alignments, teacher supports, and discovery tools.',
    color: '#4aa36a',
    tags: ['partnerships', 'supports', 'table'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-1',
    parentId: 'root-6',
    title: 'Mississippi partnership note',
    type: 'text',
    content:
      'ReadWorks says that in the first two years of its Mississippi Department of Education partnership, 20% of Mississippi educators registered and 17,000 students were impacted. The same update says 87% of registered educators work in schools with 50% or more free or reduced lunch enrollment.',
    tags: ['mississippi', 'partnerships', 'impact'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-2',
    parentId: 'root-6',
    title: 'Curriculum alignments',
    type: 'link',
    content: 'Official alignments reference used for district and teacher-facing planning.',
    url: 'https://www.readworks.org/alignments',
    tags: ['alignments', 'districts', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-3',
    parentId: 'root-6',
    title: 'For partners',
    type: 'link',
    content: 'Official partnerships page covering the ReadWorks partnership model.',
    url: 'https://about.readworks.org/for-partners',
    tags: ['partners', 'official', 'statewide'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-4',
    parentId: 'root-6',
    title: 'Advanced search update',
    type: 'link',
    content: 'Official post about the new advanced search experience used in this portal as a product-operations reference.',
    url: 'https://about.readworks.org/new-advanced-search',
    tags: ['search', 'product', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-5',
    parentId: 'root-6',
    title: 'Teacher guide',
    type: 'link',
    content: 'Teacher-facing implementation guide used throughout the support workflow.',
    url: 'https://www.readworks.org/teacher-guide',
    tags: ['teacher-guide', 'support', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-6',
    parentId: 'root-6',
    title: 'Publish partner alignment FAQ',
    type: 'task',
    content: 'Make sure partner and district packets point to the same alignment and teacher-support sources.',
    completed: false,
    tags: ['faq', 'partners', 'alignment'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-7',
    parentId: null,
    title: 'Research and analytics',
    type: 'concept',
    content: 'Shared analytics layer for research notes, webinars, and cross-surface fact checking.',
    color: '#24678d',
    tags: ['analytics', 'research', 'overview'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-1',
    parentId: 'root-7',
    title: 'Impact fact pack',
    type: 'text',
    content:
      'Core public metrics in this portal: 6,000 plus texts, all 50 states, nearly 1 million educators, 11 million students each school year, and 93% reach into the nation\'s lowest-income K-8 schools.',
    tags: ['metrics', 'impact', 'fact-pack'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-2',
    parentId: 'root-7',
    title: 'Research Loops reference',
    type: 'link',
    content: 'Official Research Loops page used to ground the sample curriculum-planning tasks in this portal.',
    url: 'https://about.readworks.org/research-loops',
    tags: ['research-loops', 'curriculum', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'a-3',
    parentId: 'root-7',
    title: 'ReadWorks webinars',
    type: 'link',
    content: 'Official webinars page used for the event examples and webinar operations view.',
    url: 'https://about.readworks.org/webinars',
    tags: ['webinars', 'events', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-4',
    parentId: 'root-7',
    title: 'Refresh partner summary',
    type: 'task',
    content: 'Update the cross-team partner summary with 2026 recognition and Mississippi milestone language.',
    completed: false,
    tags: ['partners', 'summary', '2026'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-5',
    parentId: 'root-7',
    title: 'Cross-check metrics across dashboard and portal',
    type: 'task',
    content: 'Verify that the impact counts displayed in the dashboard, calendar copy, and portal notes stay aligned.',
    completed: true,
    tags: ['metrics', 'qa', 'done'],
    updatedAt: getPastDate(3),
  },
  {
    id: 'row-7',
    parentId: 'root-6',
    title: 'Action Research Guide',
    type: 'link',
    content: 'Official six-week action research guide for K-2 literacy intervention support.',
    url: 'https://about.readworks.org/action-research-guide',
    tags: ['action-research', 'intervention', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-8',
    parentId: 'root-6',
    title: 'Fall 2025 survey results',
    type: 'link',
    content: 'Official 2026 summary of survey findings from nearly 7,000 ReadWorks users.',
    url: 'https://about.readworks.org/readworks-2025-survey-results',
    tags: ['survey', 'teachers', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-9',
    parentId: 'root-6',
    title: 'Platform integrations note',
    type: 'text',
    content:
      'ReadWorks highlights integrations with ClassLink, Clever, and Google Classroom. This portal uses that fact in partner onboarding and implementation examples.',
    tags: ['integrations', 'onboarding', 'platform'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-10',
    parentId: 'root-6',
    title: 'Teacher support operating note',
    type: 'text',
    content:
      'Support content in this workspace reflects public teacher-guide, webinar, and classroom-routine materials rather than any private internal support queue.',
    tags: ['teacher-support', 'operations', 'note'],
    updatedAt: getPastDate(2),
  },
  {
    id: 't-5',
    parentId: 'c-4',
    title: 'Book Studies title set',
    type: 'text',
    content:
      'Public Book Studies examples include titles such as Wonder, Holes, Esperanza Rising, The Wild Robot, and The One and Only Ivan. The sample portal uses those recognizable anchors when it creates internal planning tasks.',
    tags: ['book-studies', 'titles', 'curriculum'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-9',
    parentId: 'c-4',
    title: 'Review title-by-title support gaps',
    type: 'task',
    content: 'Check whether Book Studies pages, teacher guidance, and aligned articles stay consistent across major novel sets.',
    completed: false,
    tags: ['book-studies', 'qa', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-10',
    parentId: 'c-3',
    title: 'Clarify monthly Article-A-Day pacing',
    type: 'task',
    content: 'Make sure internal support notes reflect the official four-plus articles per week and 15-week routine framing.',
    completed: false,
    tags: ['article-a-day', 'pacing', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-11',
    parentId: 'root-3',
    title: 'Archive February webinar recap',
    type: 'task',
    content: 'Package moderator notes and follow-up resources from the February 10 and February 24 webinars into one searchable portal thread.',
    completed: false,
    tags: ['webinars', 'archive', 'ops'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-6',
    parentId: 'root-4',
    title: 'ReadWorks 2025 survey results post',
    type: 'event',
    content: 'Official survey-results recap published January 14, 2026.',
    startDate: '2026-01-14',
    tags: ['survey', '2026', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-7',
    parentId: 'root-4',
    title: 'Action Research Guide launch',
    type: 'event',
    content: 'Official action research guide post published October 16, 2025.',
    startDate: '2025-10-16',
    tags: ['action-research', 'intervention', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-5',
    parentId: 'root-5',
    title: 'Action research card',
    type: 'image',
    content: '/readworks-action-research.svg',
    tags: ['action-research', 'guide'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-6',
    parentId: 'root-5',
    title: 'Survey insights card',
    type: 'image',
    content: '/readworks-survey-insights.svg',
    tags: ['survey', 'teachers'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-6',
    parentId: 'root-7',
    title: 'Survey insight memo',
    type: 'text',
    content:
      'ReadWorks reported 6,956 survey participants, 95% satisfaction, and a recurring teacher need for faster onboarding, stronger discovery, and more time-saving support. Those findings justify the portal\'s emphasis on guides, search, and webinar follow-up.',
    tags: ['survey', 'memo', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-7',
    parentId: 'root-7',
    title: 'ESSA evidence note',
    type: 'text',
    content:
      'The official impact page states that ReadWorks meets Tier-3 promising evidence under ESSA. This portal keeps that language in a dedicated evidence branch so partner-facing copy stays disciplined.',
    tags: ['evidence', 'essa', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-8',
    parentId: 'root-7',
    title: 'Our story',
    type: 'link',
    content: 'Official mission and history page used to ground high-level brand and product framing.',
    url: 'https://www.readworks.org/our-story',
    tags: ['mission', 'history', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'a-9',
    parentId: 'root-7',
    title: 'Impact and evidence page',
    type: 'link',
    content: 'Official page covering nationwide scale, student reach, and evidence framing.',
    url: 'https://about.readworks.org/index.html',
    tags: ['impact', 'evidence', 'official'],
    updatedAt: getPastDate(1),
  },
];
