import { ArborNode } from './types';

const getPastDate = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const initialNodes: ArborNode[] = [
  {
    id: 'root-home',
    parentId: null,
    title: 'AI root console',
    type: 'concept',
    content:
      'Natural-language home for opening existing roots or creating new top-level workspaces across the ReadWorks portal.',
    color: '#ffffff',
    tags: ['ai-home', 'home', 'assistant'],
    updatedAt: getPastDate(0),
  },
  {
    id: 'root-1',
    parentId: null,
    title: 'ReadWorks reach and mission',
    type: 'concept',
    content:
      'ReadWorks is a nonprofit literacy organization focused on improving reading comprehension through high-quality content, curriculum, and digital tools.',
    color: '#059fc5',
    tags: ['mission', 'impact', 'readworks'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'c-1',
    parentId: 'root-1',
    title: 'Scale snapshot',
    type: 'concept',
    content: 'This branch tracks the public facts used across the staff portal and dashboard surfaces.',
    tags: ['impact', 'facts', 'about'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'i-1',
    parentId: 'c-1',
    title: 'ReadWorks impact overview',
    type: 'image',
    imageUrl: '/readworks-impact-overview.svg',
    tags: ['impact', 'overview'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-1',
    parentId: 'c-1',
    title: 'Official scale note',
    type: 'text',
    content:
      'ReadWorks says it offers 6,000 plus texts, serves all 50 states, reaches nearly 1 million educators and 11 million students each school year, and reaches 93% of the nation\'s lowest-income K-8 schools. Those public metrics anchor the portal copy and sample planning views.',
    tags: ['impact', 'metrics', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-1',
    parentId: 'c-1',
    title: 'ReadWorks About',
    type: 'link',
    url: 'https://about.readworks.org/index.html',
    content: 'Official ReadWorks overview and impact page.',
    tags: ['about', 'official', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-1',
    parentId: 'c-1',
    title: 'Refresh homepage fact stack',
    type: 'task',
    completed: false,
    tags: ['metrics', 'homepage', 'content'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'c-2',
    parentId: 'root-1',
    title: '2026 recognition and messaging',
    type: 'concept',
    content: 'Track organization-level announcements that should surface in partner decks and internal talking points.',
    tags: ['recognition', 'partners', 'messaging'],
    updatedAt: getPastDate(3),
  },
  {
    id: 't-2',
    parentId: 'c-2',
    title: 'Top 25 nonprofit note',
    type: 'text',
    content:
      'ReadWorks published a January 23, 2026 update announcing that it was named a Top 25 global impact-certified nonprofit. The staff portal uses that post as a current proof point for partner-facing credibility.',
    tags: ['2026', 'impact', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-2',
    parentId: 'c-2',
    title: 'Top 25 global impact-certified nonprofit',
    type: 'link',
    url: 'https://about.readworks.org/readworks-is-a-top-25-global-impact-certified-nonprofit',
    content: 'Official January 23, 2026 recognition post.',
    tags: ['official', '2026', 'recognition'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-2',
    parentId: 'c-2',
    title: 'Add January 2026 recognition to partner packet',
    type: 'task',
    completed: false,
    tags: ['partners', 'deck', 'recognition'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-2',
    parentId: null,
    title: 'Core classroom programs',
    type: 'concept',
    content:
      'Public program workspace covering Article-A-Day, StepReads, Book Studies, and paired-text supports used across the portal.',
    color: '#24678d',
    tags: ['programs', 'classroom', 'curriculum'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'c-3',
    parentId: 'root-2',
    title: 'Article-A-Day and StepReads',
    type: 'concept',
    content: 'Daily routine, differentiated text access, and teacher support notes live together in this branch.',
    tags: ['article-a-day', 'stepreads', 'reading'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'i-2',
    parentId: 'c-3',
    title: 'Article-A-Day program card',
    type: 'image',
    imageUrl: '/readworks-article-a-day.svg',
    tags: ['article-a-day', 'card'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-3',
    parentId: 'c-3',
    title: 'Daily routine summary',
    type: 'text',
    content:
      'ReadWorks positions Article-A-Day as a short daily classroom routine. StepReads extends that work with differentiated reading support so teachers can keep more students in the same knowledge-building sequence.',
    tags: ['article-a-day', 'stepreads', 'summary'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-3',
    parentId: 'c-3',
    title: 'Article-A-Day',
    type: 'link',
    url: 'https://www.readworks.org/article-a-day',
    content: 'Official ReadWorks Article-A-Day page.',
    tags: ['official', 'article-a-day'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-4',
    parentId: 'c-3',
    title: 'StepReads',
    type: 'link',
    url: 'https://www.readworks.org/stepreads',
    content: 'Official ReadWorks StepReads page.',
    tags: ['official', 'stepreads'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-3',
    parentId: 'c-3',
    title: 'Refresh daily routine brief',
    type: 'task',
    completed: true,
    tags: ['article-a-day', 'teacher-support', 'done'],
    updatedAt: getPastDate(4),
  },
  {
    id: 'c-4',
    parentId: 'root-2',
    title: 'Book Studies and paired texts',
    type: 'concept',
    content: 'This branch holds deeper unit work, bilingual supports, and teacher implementation notes.',
    tags: ['book-studies', 'paired-texts', 'supports'],
    updatedAt: getPastDate(3),
  },
  {
    id: 't-4',
    parentId: 'c-4',
    title: 'Program stack note',
    type: 'text',
    content:
      'Book Studies gives teachers longer-form literacy units, while Spanish-English paired texts support bilingual classrooms and cross-language comprehension work. The portal uses both as real program anchors for sample curation and QA tasks.',
    tags: ['book-studies', 'bilingual', 'qa'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-5',
    parentId: 'c-4',
    title: 'Book Studies',
    type: 'link',
    url: 'https://www.readworks.org/book-studies',
    content: 'Official ReadWorks Book Studies page.',
    tags: ['official', 'book-studies'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'l-6',
    parentId: 'c-4',
    title: 'Spanish-English paired texts',
    type: 'link',
    url: 'https://www.readworks.org/spanish-english-paired-texts',
    content: 'Official bilingual paired-texts page.',
    tags: ['official', 'bilingual', 'paired-texts'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-4',
    parentId: 'c-4',
    title: 'QA bilingual resource landing copy',
    type: 'task',
    completed: false,
    tags: ['bilingual', 'content', 'qa'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-3',
    parentId: null,
    title: 'Webinar pipeline',
    type: 'concept',
    content:
      'Kanban-style working area for educator webinar operations tied to official ReadWorks webinars and public resource launches.',
    color: '#ef8e3b',
    tags: ['kanban', 'webinars', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'k-todo',
    parentId: 'root-3',
    title: 'To Do',
    type: 'concept',
    tags: ['status:todo'],
    updatedAt: getPastDate(3),
  },
  {
    id: 'k-inprog',
    parentId: 'root-3',
    title: 'In Progress',
    type: 'concept',
    tags: ['status:in-progress'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'k-done',
    parentId: 'root-3',
    title: 'Done',
    type: 'concept',
    tags: ['status:done'],
    updatedAt: getPastDate(4),
  },
  {
    id: 'task-5',
    parentId: 'k-todo',
    title: 'Draft March 24 joint webinar deck',
    type: 'task',
    content: 'Build moderator framing and teacher examples for the March 24, 2026 session with Read STOP Write.',
    completed: false,
    tags: ['webinars', '2026', 'deck'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-6',
    parentId: 'k-todo',
    title: 'Package partner follow-up resources',
    type: 'task',
    content: 'Bundle teacher guide links, alignments, and partner notes after the next webinar cycle.',
    completed: false,
    tags: ['partners', 'teacher-guide', 'follow-up'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'task-7',
    parentId: 'k-inprog',
    title: 'Confirm moderator notes for diverse learners session',
    type: 'task',
    content: 'Turn the February 24, 2026 diverse learners webinar framing into reusable support guidance.',
    completed: false,
    tags: ['webinars', 'support', 'diverse-learners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-8',
    parentId: 'k-done',
    title: 'Publish registration reminder copy',
    type: 'task',
    content: 'Initial webinar promotion copy is approved and archived in the portal.',
    completed: true,
    tags: ['webinars', 'copy', 'done'],
    updatedAt: getPastDate(5),
  },
  {
    id: 'root-4',
    parentId: null,
    title: 'Calendar operations',
    type: 'concept',
    content: 'Live scheduling workspace for editorial reviews, webinars, partner work, and internal ReadWorks operations.',
    color: '#059fc5',
    tags: ['calendar', 'workspace', 'operations', 'schedule'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-1',
    parentId: 'root-4',
    title: 'Top 25 global impact-certified nonprofit post',
    type: 'event',
    content: 'Official ReadWorks recognition post published January 23, 2026.',
    startDate: '2026-01-23',
    tags: ['recognition', '2026', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-2',
    parentId: 'root-4',
    title: 'Mississippi partnership update',
    type: 'event',
    content: 'Official partnership update published February 11, 2026.',
    startDate: '2026-02-11',
    tags: ['partnerships', 'mississippi', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-3',
    parentId: 'root-4',
    title: '5 ways to boost engagement with high-quality texts',
    type: 'event',
    content: 'Official webinar listed for February 10, 2026.',
    startDate: '2026-02-10',
    tags: ['webinars', 'teachers', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-4',
    parentId: 'root-4',
    title: 'Supporting diverse learners with high-quality content',
    type: 'event',
    content: 'Official webinar listed for February 24, 2026.',
    startDate: '2026-02-24',
    tags: ['webinars', 'diverse-learners', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-5',
    parentId: 'root-4',
    title: 'Joint webinar with Read STOP Write',
    type: 'event',
    content: 'Official webinar listed for March 24, 2026.',
    startDate: '2026-03-24',
    tags: ['webinars', 'partners', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-5',
    parentId: null,
    title: 'ReadWorks resource gallery',
    type: 'concept',
    content: 'Visual cards used by the portal for current ReadWorks programs and public organization facts.',
    color: '#2f6f9b',
    tags: ['gallery', 'cards', 'design'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-1',
    parentId: 'root-5',
    title: 'Article-A-Day card',
    type: 'image',
    content: '/readworks-article-a-day.svg',
    tags: ['article-a-day', 'programs'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-2',
    parentId: 'root-5',
    title: 'Webinars 2026 card',
    type: 'image',
    content: '/readworks-webinars-2026.svg',
    tags: ['webinars', '2026'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-3',
    parentId: 'root-5',
    title: 'Partnerships card',
    type: 'image',
    content: '/readworks-partnerships-map.svg',
    tags: ['partnerships', 'states'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-4',
    parentId: 'root-5',
    title: 'Impact overview card',
    type: 'image',
    content: '/readworks-impact-overview.svg',
    tags: ['impact', 'metrics'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-6',
    parentId: null,
    title: 'Partnerships and supports',
    type: 'concept',
    content: 'Reference table for state partnerships, alignments, teacher supports, and discovery tools.',
    color: '#4aa36a',
    tags: ['partnerships', 'supports', 'table'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-1',
    parentId: 'root-6',
    title: 'Mississippi partnership note',
    type: 'text',
    content:
      'ReadWorks says that in the first two years of its Mississippi Department of Education partnership, 20% of Mississippi educators registered and 17,000 students were impacted. The same update says 87% of registered educators work in schools with 50% or more free or reduced lunch enrollment.',
    tags: ['mississippi', 'partnerships', 'impact'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-2',
    parentId: 'root-6',
    title: 'Curriculum alignments',
    type: 'link',
    content: 'Official alignments reference used for district and teacher-facing planning.',
    url: 'https://www.readworks.org/alignments',
    tags: ['alignments', 'districts', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-3',
    parentId: 'root-6',
    title: 'For partners',
    type: 'link',
    content: 'Official partnerships page covering the ReadWorks partnership model.',
    url: 'https://about.readworks.org/for-partners',
    tags: ['partners', 'official', 'statewide'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-4',
    parentId: 'root-6',
    title: 'Advanced search update',
    type: 'link',
    content: 'Official post about the new advanced search experience used in this portal as a product-operations reference.',
    url: 'https://about.readworks.org/new-advanced-search',
    tags: ['search', 'product', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-5',
    parentId: 'root-6',
    title: 'Teacher guide',
    type: 'link',
    content: 'Teacher-facing implementation guide used throughout the support workflow.',
    url: 'https://www.readworks.org/teacher-guide',
    tags: ['teacher-guide', 'support', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-6',
    parentId: 'root-6',
    title: 'Publish partner alignment FAQ',
    type: 'task',
    content: 'Make sure partner and district packets point to the same alignment and teacher-support sources.',
    completed: false,
    tags: ['faq', 'partners', 'alignment'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-7',
    parentId: null,
    title: 'Operations dashboard',
    type: 'concept',
    content: 'Primary command view for ReadWorks program activity, evidence, research signals, and upcoming operating work.',
    color: '#24678d',
    tags: ['dashboard', 'analytics', 'research', 'overview', 'workspace'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-1',
    parentId: 'root-7',
    title: 'Impact fact pack',
    type: 'text',
    content:
      'Core public metrics in this portal: 6,000 plus texts, all 50 states, nearly 1 million educators, 11 million students each school year, and 93% reach into the nation\'s lowest-income K-8 schools.',
    tags: ['metrics', 'impact', 'fact-pack'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-2',
    parentId: 'root-7',
    title: 'Research Loops reference',
    type: 'link',
    content: 'Official Research Loops page used to ground the sample curriculum-planning tasks in this portal.',
    url: 'https://about.readworks.org/research-loops',
    tags: ['research-loops', 'curriculum', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'a-3',
    parentId: 'root-7',
    title: 'ReadWorks webinars',
    type: 'link',
    content: 'Official webinars page used for the event examples and webinar operations view.',
    url: 'https://about.readworks.org/webinars',
    tags: ['webinars', 'events', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-4',
    parentId: 'root-7',
    title: 'Refresh partner summary',
    type: 'task',
    content: 'Update the cross-team partner summary with 2026 recognition and Mississippi milestone language.',
    completed: false,
    tags: ['partners', 'summary', '2026'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-5',
    parentId: 'root-7',
    title: 'Cross-check metrics across dashboard and portal',
    type: 'task',
    content: 'Verify that the impact counts displayed in the dashboard, calendar copy, and portal notes stay aligned.',
    completed: true,
    tags: ['metrics', 'qa', 'done'],
    updatedAt: getPastDate(3),
  },
  {
    id: 'row-7',
    parentId: 'root-6',
    title: 'Action Research Guide',
    type: 'link',
    content: 'Official six-week action research guide for K-2 literacy intervention support.',
    url: 'https://about.readworks.org/readworks-action-research-guide.html',
    tags: ['action-research', 'intervention', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-8',
    parentId: 'root-6',
    title: 'Fall 2025 survey results',
    type: 'link',
    content: 'Official 2026 summary of survey findings from nearly 7,000 ReadWorks users.',
    url: 'https://about.readworks.org/blog/readworks-insights-fall-2025-national-user-survey-results',
    tags: ['survey', 'teachers', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-9',
    parentId: 'root-6',
    title: 'Platform integrations note',
    type: 'text',
    content:
      'ReadWorks highlights integrations with ClassLink, Clever, and Google Classroom. This portal uses that fact in partner onboarding and implementation examples.',
    tags: ['integrations', 'onboarding', 'platform'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-10',
    parentId: 'root-6',
    title: 'Teacher support operating note',
    type: 'text',
    content:
      'Support content in this workspace reflects public teacher-guide, webinar, and classroom-routine materials rather than any private internal support queue.',
    tags: ['teacher-support', 'operations', 'note'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-11',
    parentId: 'root-6',
    title: 'Our partners',
    type: 'link',
    content: 'Official partners page covering district, philanthropic, and institutional collaborators.',
    url: 'https://about.readworks.org/our-partners.html',
    tags: ['partners', 'official', 'network'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-5',
    parentId: 'c-4',
    title: 'Book Studies title set',
    type: 'text',
    content:
      'Public Book Studies examples include titles such as Wonder, Holes, Esperanza Rising, The Wild Robot, and The One and Only Ivan. The sample portal uses those recognizable anchors when it creates internal planning tasks.',
    tags: ['book-studies', 'titles', 'curriculum'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-9',
    parentId: 'c-4',
    title: 'Review title-by-title support gaps',
    type: 'task',
    content: 'Check whether Book Studies pages, teacher guidance, and aligned articles stay consistent across major novel sets.',
    completed: false,
    tags: ['book-studies', 'qa', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-10',
    parentId: 'c-3',
    title: 'Clarify monthly Article-A-Day pacing',
    type: 'task',
    content: 'Make sure internal support notes reflect the official four-plus articles per week and 15-week routine framing.',
    completed: false,
    tags: ['article-a-day', 'pacing', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-11',
    parentId: 'root-3',
    title: 'Archive February webinar recap',
    type: 'task',
    content: 'Package moderator notes and follow-up resources from the February 10 and February 24 webinars into one searchable portal thread.',
    completed: false,
    tags: ['webinars', 'archive', 'ops'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-6',
    parentId: 'root-4',
    title: 'ReadWorks 2025 survey results post',
    type: 'event',
    content: 'Official survey-results recap published February 4, 2026.',
    startDate: '2026-02-04',
    tags: ['survey', '2026', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-7',
    parentId: 'root-4',
    title: 'Action Research Guide launch',
    type: 'event',
    content: 'Official action research guide post published October 16, 2025.',
    startDate: '2025-10-16',
    tags: ['action-research', 'intervention', 'public'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-5',
    parentId: 'root-5',
    title: 'Action research card',
    type: 'image',
    content: '/readworks-action-research.svg',
    tags: ['action-research', 'guide'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-6',
    parentId: 'root-5',
    title: 'Survey insights card',
    type: 'image',
    content: '/readworks-survey-insights.svg',
    tags: ['survey', 'teachers'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-6',
    parentId: 'root-7',
    title: 'Survey insight memo',
    type: 'text',
    content:
      'ReadWorks reported 6,956 survey participants, 95% satisfaction, and a recurring teacher need for faster onboarding, stronger discovery, and more time-saving support. Those findings justify the portal\'s emphasis on guides, search, and webinar follow-up.',
    tags: ['survey', 'memo', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-7',
    parentId: 'root-7',
    title: 'ESSA evidence note',
    type: 'text',
    content:
      'The official impact page states that ReadWorks meets Tier-3 promising evidence under ESSA. This portal keeps that language in a dedicated evidence branch so partner-facing copy stays disciplined.',
    tags: ['evidence', 'essa', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-8',
    parentId: 'root-7',
    title: 'Our story',
    type: 'link',
    content: 'Official mission and history page used to ground high-level brand and product framing.',
    url: 'https://www.readworks.org/our-story',
    tags: ['mission', 'history', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'a-9',
    parentId: 'root-7',
    title: 'Impact and evidence page',
    type: 'link',
    content: 'Official page covering nationwide scale, student reach, and evidence framing.',
    url: 'https://about.readworks.org/index.html',
    tags: ['impact', 'evidence', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-10',
    parentId: 'root-7',
    title: 'Strategic plan 2022-2025',
    type: 'link',
    content: 'Official strategic plan page used to ground district strategy, differentiation, and research-growth language.',
    url: 'https://about.readworks.org/readworks2025.html',
    tags: ['strategy', 'districts', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-8',
    parentId: null,
    title: 'Professional learning studio',
    type: 'concept',
    content: 'District-facing professional learning, webinar, and implementation workspace grounded in official ReadWorks PD offerings.',
    color: '#4aa36a',
    tags: ['table', 'professional-learning', 'pd', 'districts'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pl-1',
    parentId: 'root-8',
    title: 'Professional learning packages',
    type: 'link',
    content: 'Official page for ReadWorks professional learning sessions and district packages.',
    url: 'https://about.readworks.org/professional-learning.html',
    tags: ['pd', 'districts', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pl-2',
    parentId: 'root-8',
    title: 'Philadelphia regional support note',
    type: 'text',
    content:
      'ReadWorks publicly highlights customized virtual PD in Philadelphia and reports use by 46% of teachers and 38% of students in the School District of Philadelphia during the prior school year. The portal uses that page as a concrete example of region-specific support work.',
    tags: ['pd', 'philadelphia', 'regional-support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pl-3',
    parentId: 'root-8',
    title: 'Philadelphia support page',
    type: 'link',
    content: 'Official regional support page with examples of customized PD topics.',
    url: 'https://about.readworks.org/phillysupport.html',
    tags: ['philadelphia', 'pd', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pl-4',
    parentId: 'root-8',
    title: 'Package science-of-reading PD brief',
    type: 'task',
    content: 'Turn public PD language into a concise internal brief for districts asking about implementation and teacher training.',
    completed: false,
    tags: ['pd', 'science-of-reading', 'districts'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pl-6',
    parentId: 'root-8',
    title: 'Administrator inquiry',
    type: 'link',
    content: 'Official admin-facing inquiry page referencing million-plus teacher reach and evidence certifications.',
    url: 'https://about.readworks.org/admininquiry.html',
    tags: ['administrators', 'districts', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pl-5',
    parentId: 'root-8',
    title: 'Professional learning guide routing',
    type: 'text',
    content:
      'This workspace keeps together webinar references, implementation materials, and outreach notes so partner teams can route schools to the right PD package quickly.',
    tags: ['pd', 'operations', 'routing'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'root-9',
    parentId: null,
    title: 'Platform and access',
    type: 'concept',
    content: 'Platform operations workspace for integrations, student access, search, and digital classroom workflows.',
    color: '#2f6f9b',
    tags: ['table', 'platform', 'integrations', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-1',
    parentId: 'root-9',
    title: 'Tech checklist',
    type: 'document',
    content: 'Official technical checklist covering approved applications and classroom setup details.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/copy_of_readworks_tech_checklist__8.5_x_11_in_.pdf',
    tags: ['tech', 'checklist', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-2',
    parentId: 'root-9',
    title: 'Digital features guide',
    type: 'document',
    content: 'Official student-facing digital features guide used to ground implementation notes.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/digital_features_guide_-_student__1_.pdf',
    tags: ['digital-features', 'students', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-3',
    parentId: 'root-9',
    title: 'Search filters workflow',
    type: 'link',
    content: 'Official support article describing the library filter model.',
    url: 'https://help.readworks.org/article/66-how-do-i-use-the-search-filters',
    tags: ['search', 'filters', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-4',
    parentId: 'root-9',
    title: 'Google Classroom roster sync note',
    type: 'text',
    content:
      'ReadWorks support documentation describes syncing Google Classroom rosters and notes that assignments publish into the Google Classroom stream. That gives the portal a concrete platform-ops workflow to model.',
    tags: ['google-classroom', 'roster', 'platform'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-5',
    parentId: 'root-9',
    title: 'Quick start guide for students',
    type: 'document',
    content: 'Official student onboarding guide for Google sign-in classes.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/quick_start_guide.google_signin.pdf',
    tags: ['students', 'onboarding', 'official'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'pf-6',
    parentId: 'root-9',
    title: 'Refresh shared-device support note',
    type: 'task',
    content: 'Keep shared-device and Google account chooser setup guidance aligned with current support-center language.',
    completed: false,
    tags: ['devices', 'google', 'support'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-7',
    parentId: 'root-9',
    title: 'Google Classroom sync workflow',
    type: 'link',
    content: 'Official help article describing how teachers sync Google Classroom rosters into ReadWorks.',
    url: 'https://help.readworks.org/article/62-how-do-i-sync-my-google-classroom-account',
    tags: ['google-classroom', 'sync', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-8',
    parentId: 'root-9',
    title: 'Shared-device chooser note',
    type: 'text',
    content:
      'ReadWorks support documentation tells schools using shared devices to select the correct Google account before launching the ReadWorks add-on or syncing a class. That operational note now lives in the platform branch instead of being buried in the calendar.',
    tags: ['shared-devices', 'google', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'pf-9',
    parentId: 'root-9',
    title: 'SOC 2 certification',
    type: 'link',
    content: 'Official trust page confirming ReadWorks holds SOC 2 certification for its platform environment.',
    url: 'https://about.readworks.org/soc2-certification.html',
    tags: ['security', 'trust', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-10',
    parentId: null,
    title: 'Early literacy lab',
    type: 'concept',
    content: 'Workspace for decodables, science-of-reading supports, and K-2 classroom implementation materials.',
    color: '#ef8e3b',
    tags: ['concept', 'early-literacy', 'decodables', 'science-of-reading'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'el-1',
    parentId: 'root-10',
    title: 'Decodables official page',
    type: 'link',
    content: 'Official ReadWorks decodables page with Fundations- and UFLI-aligned guidance.',
    url: 'https://about.readworks.org/decodable-texts.html',
    tags: ['decodables', 'fundations', 'ufli', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'el-2',
    parentId: 'root-10',
    title: 'Science of reading statement',
    type: 'document',
    content: 'Official ReadWorks statement on the science of reading and the role of supplemental supports.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/official_statement_.pdf',
    tags: ['science-of-reading', 'official', 'research'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'el-3',
    parentId: 'root-10',
    title: 'Decodables implementation note',
    type: 'text',
    content:
      'ReadWorks says most Fundations-aligned decodables are at least 90% decodable and recommends establishing the Article-A-Day routine before folding decodables into the week. This is now a core early-literacy planning note in the portal.',
    tags: ['decodables', 'implementation', 'early-literacy'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'el-4',
    parentId: 'root-10',
    title: 'ReadWorks and UFLI webinar',
    type: 'link',
    content: 'Official webinar post on decodable texts and UFLI-aligned supports.',
    url: 'https://about.readworks.org/blog/strengthening-reading-comprehension-through-word-recognition-a-webinar-with-readworks-and-ufli',
    tags: ['ufli', 'webinar', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'el-5',
    parentId: 'root-10',
    title: 'Map decodables to AAD sets',
    type: 'task',
    content: 'Extend the internal planning map showing which decodable bundles pair best with existing Article-A-Day topics.',
    completed: false,
    tags: ['decodables', 'article-a-day', 'mapping'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-11',
    parentId: null,
    title: 'Licensing and sustainability',
    type: 'concept',
    content: 'Org and partner-facing workspace for financial efficiency, licensing, and long-term sustainability messaging.',
    color: '#24678d',
    tags: ['table', 'licensing', 'financials', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ls-1',
    parentId: 'root-11',
    title: 'Our financials',
    type: 'link',
    content: 'Official financials page with annual cost-per-student and transparency references.',
    url: 'https://about.readworks.org/our-financials.html',
    tags: ['financials', 'official', 'transparency'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ls-2',
    parentId: 'root-11',
    title: 'Licensing',
    type: 'link',
    content: 'Official licensing page for companies and publishers using ReadWorks content outside permitted uses.',
    url: 'https://about.readworks.org/licensing.html',
    tags: ['licensing', 'official', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ls-3',
    parentId: 'root-11',
    title: 'Efficiency note',
    type: 'text',
    content:
      'ReadWorks states that nationwide annual cost is 29 cents per student and $3.40 per educator. This portal uses that language carefully in partner and sustainability briefing drafts.',
    tags: ['cost', 'financials', 'partners'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ls-4',
    parentId: 'root-11',
    title: '2023 annual report',
    type: 'document',
    content: 'Official annual report covering mission, pillars, and the organization’s research and impact framing.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/readworks_2023_annual_report.pdf',
    tags: ['annual-report', 'research', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ls-5',
    parentId: 'root-11',
    title: 'Update partner sustainability memo',
    type: 'task',
    content: 'Refresh the partner memo with financial efficiency, transparency, and licensing language pulled from official pages.',
    completed: false,
    tags: ['partners', 'memo', 'financials'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ls-6',
    parentId: 'root-11',
    title: 'FY24 audit report',
    type: 'document',
    content: 'Official FY24 audit report with updated organizational financial detail and operating context.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/readworks_audit_report_fy24.pdf',
    tags: ['financials', 'audit', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-12',
    parentId: null,
    title: 'Student experience studio',
    type: 'concept',
    content: 'Workspace for independent reading, student access, differentiation tools, and offline support grounded in official ReadWorks student-facing materials.',
    color: '#059fc5',
    tags: ['student-experience', 'library', 'access', 'research'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-1',
    parentId: 'root-12',
    title: 'Student Library',
    type: 'link',
    content: 'Official student-library page for independent reading and choice-based reading growth.',
    url: 'https://about.readworks.org/student-library.html',
    tags: ['student-library', 'official', 'students'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-2',
    parentId: 'root-12',
    title: 'Student Library one-pager',
    type: 'document',
    content: 'Official one-pager describing the student library, daily recommendations, and teacher visibility into reading volume.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/student_library_one-pager.pdf',
    tags: ['student-library', 'document', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-3',
    parentId: 'root-12',
    title: 'Offline mode for students',
    type: 'link',
    content: 'Official offline-mode guide covering download flow and submission timing after reconnect.',
    url: 'https://about.readworks.org/offline-mode.html',
    tags: ['offline-mode', 'students', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-4',
    parentId: 'root-12',
    title: 'Differentiation with digital supports',
    type: 'link',
    content: 'Official page describing text-to-speech, audio, and offline-mode support for student access.',
    url: 'https://about.readworks.org/differentiation-tools.html',
    tags: ['differentiation', 'digital-supports', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-5',
    parentId: 'root-12',
    title: 'Independent reading operating note',
    type: 'text',
    content:
      'The official student-library one-pager says students can access passages from kindergarten to two grades above their current grade, read without assessments for the joy of learning, and receive daily recommendations based on interest and reading history. That gives this portal a much stronger student-experience branch than generic “reading practice” copy.',
    tags: ['students', 'independent-reading', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-6',
    parentId: 'root-12',
    title: 'Map library and offline support scripts',
    type: 'task',
    content: 'Turn the official student-library and offline-mode materials into cleaner partner, teacher, and family support playbooks.',
    completed: false,
    tags: ['students', 'support', 'playbook'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-7',
    parentId: 'root-12',
    title: 'Class Book of Knowledge',
    type: 'link',
    content: 'Official help article for the shared class knowledge notebook tied to Article-A-Day routines.',
    url: 'https://help.readworks.org/article/86-how-do-i-use-the-class-book-of-knowledge',
    tags: ['book-of-knowledge', 'classroom', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-8',
    parentId: 'root-12',
    title: 'Big Book of Knowledge',
    type: 'link',
    content: 'Official help article showing how students find their knowledge notebook after reading assignments.',
    url: 'https://help.readworks.org/article/85-how-do-my-students-find-their-big-book-of-knowledge',
    tags: ['book-of-knowledge', 'students', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'sx-9',
    parentId: 'root-12',
    title: 'Family Book of Knowledge support',
    type: 'link',
    content: 'Official family-facing help article for accessing a child’s Big Book of Knowledge.',
    url: 'https://help.readworks.org/article/93-how-do-i-find-my-child-s-big-book-of-knowledge',
    tags: ['families', 'book-of-knowledge', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-13',
    parentId: null,
    title: 'Adoption and campaigns',
    type: 'concept',
    content: 'Cross-functional workspace for public updates, onboarding campaigns, Google ecosystem support, and adoption messaging.',
    color: '#4aa36a',
    tags: ['adoption', 'campaigns', 'communications', 'platform'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-1',
    parentId: 'root-13',
    title: 'February 2026 update',
    type: 'link',
    content: 'Official February 24, 2026 update tying together survey results, research, and organizational news.',
    url: 'https://about.readworks.org/blog/readworks-february-2026-update',
    tags: ['2026', 'updates', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-2',
    parentId: 'root-13',
    title: 'Google for Education partnership',
    type: 'link',
    content: 'Official partnership post covering the Google Classroom add-on, ReadAlong support, and Sign in with Google.',
    url: 'https://about.readworks.org/blog/exciting-partnership-with-google-for-education-enhances-readworks-accessibility-and-integration?category=social&source=linktree',
    tags: ['google', 'classroom', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-3',
    parentId: 'root-13',
    title: 'Recommended edtech applications PDF',
    type: 'document',
    content: 'Official district checklist for approving ReadWorks and related classroom setup steps.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/add_readworks_to_your_recommended_edtech_applications_list__3_.pdf',
    tags: ['districts', 'approval', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-4',
    parentId: 'root-13',
    title: 'Back-to-school access checklist',
    type: 'link',
    content: 'Official setup post telling Google users to verify that ReadWorks is installed as a Classroom add-on before school starts.',
    url: 'https://about.readworks.org/blog/make-sure-readworks-is-ready-to-go-for-your-students',
    tags: ['back-to-school', 'google', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-5',
    parentId: 'root-13',
    title: 'Adoption messaging note',
    type: 'text',
    content:
      'The latest adoption-facing stack is more concrete now: ReadWorks publicly points districts to approved-app guidance, Google Classroom setup, sign-in simplification, student-library access, and monthly update posts rather than only high-level mission language.',
    tags: ['adoption', 'messaging', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-6',
    parentId: 'root-13',
    title: 'Refresh onboarding campaign brief',
    type: 'task',
    content: 'Rebuild the onboarding brief around Google add-on setup, student-library access, offline mode, and 2026 survey-informed support priorities.',
    completed: false,
    tags: ['campaigns', 'onboarding', 'brief'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-7',
    parentId: 'root-13',
    title: 'Earth Day illustration contest',
    type: 'document',
    content: 'Official 2026 contest submission sheet that gives the campaigns branch a concrete student-engagement artifact with a live spring deadline.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/nfwf_submission_sheet_2026.pdf',
    tags: ['campaigns', 'students', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-8',
    parentId: 'root-13',
    title: 'Our supporters',
    type: 'link',
    content: 'Official supporters page listing foundations, corporate donors, and major partner organizations.',
    url: 'https://about.readworks.org/our-supporters.html',
    tags: ['supporters', 'funding', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-9',
    parentId: 'root-13',
    title: 'Corporate partnerships one-pager',
    type: 'document',
    content: 'Official one-pager for corporate and foundation partnerships used in external outreach.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/readworks_corporate_partnership_one-pager.pdf',
    tags: ['partners', 'corporate', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-10',
    parentId: 'root-13',
    title: 'Earth Day 2026 illustration contest',
    type: 'link',
    content: 'Official 2026 campaign page for the Earth Day student illustration contest.',
    url: 'https://about.readworks.org/earthday2026.html',
    tags: ['campaigns', 'earth-day', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-11',
    parentId: 'root-13',
    title: 'Earth Day submission form',
    type: 'document',
    content: 'Official 2026 submission-sheet PDF for Earth Day contest entry collection.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/nfwf_submission_sheet_2026.pdf',
    tags: ['campaigns', 'earth-day', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'ac-12',
    parentId: 'root-13',
    title: 'Partner network reference',
    type: 'link',
    content: 'Official partners overview used to support campaign and outreach narratives.',
    url: 'https://about.readworks.org/our-partners.html',
    tags: ['partners', 'campaigns', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-14',
    parentId: null,
    title: 'Research and evidence lab',
    type: 'concept',
    content: 'Dedicated research branch for public studies, differentiation briefs, and evidence framing that support ReadWorks program decisions.',
    color: '#24678d',
    tags: ['research', 'evidence', 'studies'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'rl-1',
    parentId: 'root-14',
    title: 'ReadWorks research',
    type: 'link',
    content: 'Official research page collecting efficacy studies, practitioner research, and evidence summaries.',
    url: 'https://about.readworks.org/the-research.html',
    tags: ['research', 'official', 'studies'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'rl-2',
    parentId: 'root-14',
    title: 'Article-A-Day differentiation one-pager',
    type: 'document',
    content: 'Official one-pager describing differentiation choices inside the Article-A-Day routine.',
    url: 'https://about.readworks.org/uploads/7/9/6/7/79679564/aad_differentiation_one-pager.pdf',
    tags: ['article-a-day', 'differentiation', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'rl-3',
    parentId: 'root-14',
    title: 'Research evidence note',
    type: 'text',
    content:
      'ReadWorks says Article-A-Day has been linked to gains in reading comprehension, social studies knowledge, and science knowledge, and the research page also highlights digital-support findings from partners such as Digital Promise and NYU. This branch is where evidence claims should be checked before they reach dashboard copy.',
    tags: ['research', 'evidence', 'note'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'rl-4',
    parentId: 'root-14',
    title: 'Validate evidence language against current studies',
    type: 'task',
    content: 'Use the public research page and linked briefs to keep ESSA, differentiation, and comprehension claims disciplined across the portal.',
    completed: false,
    tags: ['research', 'evidence', 'qa'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-15',
    parentId: null,
    title: 'Family and afterschool pathways',
    type: 'concept',
    content: 'Community-facing branch for summer use, afterschool implementation, and family support flows built from official ReadWorks materials.',
    color: '#ef8e3b',
    tags: ['families', 'afterschool', 'summer', 'community'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'fa-1',
    parentId: 'root-15',
    title: 'Summer workbook',
    type: 'link',
    content: 'Official summer program page for helping students keep reading and knowledge-building habits active during break.',
    url: 'https://about.readworks.org/summer.html',
    tags: ['summer', 'students', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'fa-2',
    parentId: 'root-15',
    title: 'Y Afterschool',
    type: 'link',
    content: 'Official afterschool page showing how ReadWorks is used in YMCA afterschool settings.',
    url: 'https://about.readworks.org/y-afterschool.html',
    tags: ['afterschool', 'community', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'fa-3',
    parentId: 'root-15',
    title: 'Article-A-Day for hybrid and remote teaching',
    type: 'link',
    content: 'Official implementation page for running the Article-A-Day routine in hybrid or remote environments.',
    url: 'https://about.readworks.org/article-a-day-routine-hybrid-remote.html',
    tags: ['article-a-day', 'remote', 'official'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'fa-4',
    parentId: 'root-15',
    title: 'Community implementation note',
    type: 'text',
    content:
      'The summer, afterschool, and hybrid-routine pages make ReadWorks easier to frame as a year-round support system rather than a classroom-only product. This page gives the portal a public basis for family and community examples.',
    tags: ['families', 'community', 'operations'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'fa-5',
    parentId: 'root-15',
    title: 'Build family-facing quick-start packet',
    type: 'task',
    content: 'Combine summer, afterschool, hybrid-routine, and family Book of Knowledge resources into one support packet.',
    completed: false,
    tags: ['families', 'packet', 'support'],
    updatedAt: getPastDate(1),
  },
];
