import { ArborNode } from './types';

const getPastDate = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const initialNodes: ArborNode[] = [
  {
    id: 'root-1',
    parentId: null,
    title: 'Oracle Fusion AI Agent Studio',
    type: 'concept',
    content:
      'Oracle AI Agent Studio for Fusion Applications is built natively in Oracle Fusion Applications and runs on Oracle Cloud Infrastructure.',
    color: '#c74634',
    tags: ['fusion', 'ai', 'applications', 'oracle'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'c-1',
    parentId: 'root-1',
    title: 'Embedded in Fusion Applications',
    type: 'concept',
    content: 'The rollout model centers on AI agents being configured where application work already happens.',
    tags: ['fusion', 'ai', 'hcm', 'erp'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'i-1',
    parentId: 'c-1',
    title: 'Fusion AI Agent Studio overview',
    type: 'image',
    imageUrl: '/oracle-fusion-ai-agent-studio.svg',
    tags: ['fusion', 'ai', 'overview'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-1',
    parentId: 'c-1',
    title: 'Oracle reference note',
    type: 'text',
    content:
      'Oracle positions AI Agent Studio as a way to create, extend, deploy, and manage AI agents across Oracle Fusion Applications. The sample portal uses that public positioning as the planning anchor for product, enablement, and event work.',
    tags: ['reference', 'fusion', 'ai'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-1',
    parentId: 'c-1',
    title: 'Oracle AI Agents for Fusion Applications',
    type: 'link',
    url: 'https://www.oracle.com/applications/ai/ai-agents/',
    content: 'Official Oracle page for Fusion Applications AI agents and AI Agent Studio.',
    tags: ['oracle', 'fusion', 'ai', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-1',
    parentId: 'c-1',
    title: 'Review HCM and ERP agent scenarios',
    type: 'task',
    completed: false,
    tags: ['planning', 'fusion', 'hcm', 'erp'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'c-2',
    parentId: 'root-1',
    title: 'Governance and rollout',
    type: 'concept',
    content: 'The portal tracks approvals, data access, and field readiness before Oracle teams expand agent usage.',
    tags: ['governance', 'rollout', 'ai'],
    updatedAt: getPastDate(3),
  },
  {
    id: 't-2',
    parentId: 'c-2',
    title: 'Governance brief',
    type: 'text',
    content:
      'Use the portal for a shared view of agent governance, rollout sequencing, and field messaging. This keeps the sample grounded in public Oracle product direction without claiming internal roadmap details.',
    tags: ['governance', 'brief'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'task-2',
    parentId: 'c-2',
    title: 'Validate security and approval notes',
    type: 'task',
    completed: false,
    tags: ['security', 'approval', 'planning'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-2',
    parentId: null,
    title: 'Oracle AI Database 26ai',
    type: 'concept',
    content:
      'Oracle AI Database 26ai is positioned as an AI-first database with vector search, in-database AI, and AI support across the full data and app stack.',
    color: '#5b6dee',
    tags: ['database', 'ai', 'oci', 'oracle'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'c-3',
    parentId: 'root-2',
    title: 'AI in the data stack',
    type: 'concept',
    content: 'This area keeps launch notes for vector search, AI app development, and database positioning.',
    tags: ['database', 'vector-search', 'development'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'i-2',
    parentId: 'c-3',
    title: 'Oracle AI Database card',
    type: 'image',
    imageUrl: '/oracle-ai-database-26ai.svg',
    tags: ['database', 'ai'],
    updatedAt: getPastDate(1),
  },
  {
    id: 't-3',
    parentId: 'c-3',
    title: 'Launch summary',
    type: 'text',
    content:
      'Oracle describes AI Database 26ai as architected for the full data and development stack, including AI Vector Search and in-database AI. The sample portal uses that public release framing directly.',
    tags: ['database', 'launch', 'ai'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-2',
    parentId: 'c-3',
    title: 'Oracle AI Database official page',
    type: 'link',
    url: 'https://www.oracle.com/database/ai-database/',
    content: 'Oracle overview page for AI Database 26ai.',
    tags: ['oracle', 'database', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-3',
    parentId: 'c-3',
    title: 'Refresh vector search briefing notes',
    type: 'task',
    completed: true,
    tags: ['database', 'briefing', 'planning'],
    updatedAt: getPastDate(4),
  },
  {
    id: 'c-4',
    parentId: 'root-2',
    title: 'OCI footprint',
    type: 'concept',
    content: 'Track Oracle Cloud Infrastructure footprint facts and service-availability messaging used across the portal.',
    tags: ['oci', 'regions', 'infrastructure'],
    updatedAt: getPastDate(2),
  },
  {
    id: 't-4',
    parentId: 'c-4',
    title: 'OCI network facts',
    type: 'text',
    content:
      'Oracle lists 50+ public cloud regions across 28 countries, 200+ cloud services, 2 sovereign regions, and 23 dedicated regions on its official OCI regions page.',
    tags: ['oci', 'regions', 'data'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'l-3',
    parentId: 'c-4',
    title: 'Oracle Cloud Infrastructure regions',
    type: 'link',
    url: 'https://www.oracle.com/cloud/public-cloud-regions/',
    content: 'Official Oracle Cloud Infrastructure regions and services reference.',
    tags: ['oci', 'regions', 'reference'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-3',
    parentId: null,
    title: 'JavaOne 2026 launch board',
    type: 'concept',
    content: 'Kanban view for public-event support tied to JavaOne 2026 in Redwood Shores on March 17-19.',
    color: '#f3b239',
    tags: ['kanban', 'javaone', 'events', 'planning'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'k-todo',
    parentId: 'root-3',
    title: 'To Do',
    type: 'concept',
    tags: ['status:todo'],
    updatedAt: getPastDate(3),
  },
  {
    id: 'k-inprog',
    parentId: 'root-3',
    title: 'In Progress',
    type: 'concept',
    tags: ['status:in-progress'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'k-done',
    parentId: 'root-3',
    title: 'Done',
    type: 'concept',
    tags: ['status:done'],
    updatedAt: getPastDate(4),
  },
  {
    id: 'task-4',
    parentId: 'k-todo',
    title: 'Finalize JavaOne speaker handoff',
    type: 'task',
    content: 'Lock operator notes and speaker support around the March 17-19 JavaOne window.',
    completed: false,
    tags: ['javaone', 'events', 'planning'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-5',
    parentId: 'k-todo',
    title: 'Publish attendee logistics brief',
    type: 'task',
    content: 'Package the venue, room, and timing notes for Redwood Shores field teams.',
    completed: false,
    tags: ['javaone', 'field', 'communications'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'task-6',
    parentId: 'k-inprog',
    title: 'Review keynote demo readiness',
    type: 'task',
    content: 'Check demo timing and transitions for the opening JavaOne session.',
    completed: false,
    tags: ['javaone', 'demo', 'engineering'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-7',
    parentId: 'k-inprog',
    title: 'Confirm developer social schedule',
    type: 'task',
    content: 'Coordinate the public social lineup around JavaOne announcements.',
    completed: false,
    tags: ['javaone', 'marketing', 'social'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'task-8',
    parentId: 'k-done',
    title: 'Publish JavaOne landing page copy',
    type: 'task',
    content: 'Initial event language and registration framing approved.',
    completed: true,
    tags: ['javaone', 'copywriting', 'done'],
    updatedAt: getPastDate(5),
  },
  {
    id: 'root-4',
    parentId: null,
    title: 'Oracle event calendar 2026',
    type: 'concept',
    content: 'Calendar view for official Oracle events used in the sample portal.',
    color: '#c74634',
    tags: ['calendar', 'events', 'oracle'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-1',
    parentId: 'root-4',
    title: 'JavaOne 2026 Day 1',
    type: 'event',
    content: 'Oracle Java developer event opening day.',
    startDate: '2026-03-17',
    tags: ['javaone', 'developer', 'event'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-2',
    parentId: 'root-4',
    title: 'JavaOne 2026 Day 2',
    type: 'event',
    content: 'Day two sessions and demos for JavaOne 2026.',
    startDate: '2026-03-18',
    tags: ['javaone', 'developer', 'event'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-3',
    parentId: 'root-4',
    title: 'JavaOne 2026 Day 3',
    type: 'event',
    content: 'Final day of JavaOne 2026 in Redwood Shores.',
    startDate: '2026-03-19',
    tags: ['javaone', 'developer', 'event'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-4',
    parentId: 'root-4',
    title: 'Oracle AI World Tour Chicago',
    type: 'event',
    content: 'Official 2026 Chicago stop on the Oracle AI World Tour.',
    startDate: '2026-04-07',
    tags: ['ai', 'tour', 'event'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'event-5',
    parentId: 'root-4',
    title: 'Oracle Health and Life Sciences Summit',
    type: 'event',
    content: 'Official Oracle summit scheduled for September 22-24, 2026 in Orlando.',
    startDate: '2026-09-22',
    tags: ['health', 'life-sciences', 'event'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-5',
    parentId: null,
    title: 'Oracle program gallery',
    type: 'concept',
    content: 'Visual cards for public Oracle programs and platform facts.',
    color: '#e25d3f',
    tags: ['gallery', 'oracle', 'design'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-1',
    parentId: 'root-5',
    title: 'JavaOne 2026 card',
    type: 'image',
    content: '/oracle-javaone-2026.svg',
    tags: ['javaone', 'events'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-2',
    parentId: 'root-5',
    title: 'Fusion AI Agent Studio card',
    type: 'image',
    content: '/oracle-fusion-ai-agent-studio.svg',
    tags: ['fusion', 'ai'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-3',
    parentId: 'root-5',
    title: 'Oracle AI Database 26ai card',
    type: 'image',
    content: '/oracle-ai-database-26ai.svg',
    tags: ['database', 'ai'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'img-4',
    parentId: 'root-5',
    title: 'OCI footprint card',
    type: 'image',
    content: '/oracle-oci-footprint.svg',
    tags: ['oci', 'regions'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-6',
    parentId: null,
    title: 'Oracle University enablement',
    type: 'concept',
    content: 'Table-style workspace for learning, certification, and support-enablement references.',
    color: '#4da866',
    tags: ['table', 'research', 'data', 'enablement'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-1',
    parentId: 'root-6',
    title: 'MyLearn overview',
    type: 'text',
    content: 'Oracle University MyLearn is the portal reference for role-based learning, labs, and certification preparation.',
    tags: ['learning', 'mylearn', 'enablement'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-2',
    parentId: 'root-6',
    title: 'Oracle University Learning Explorer',
    type: 'document',
    content: 'Oracle University page used here as a public reference for free learning and certification prep.',
    url: 'https://www.oracle.com/education/oracle-learning-explorer/',
    tags: ['learning', 'document', 'certification'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'row-3',
    parentId: 'root-6',
    title: 'Oracle Support Rewards',
    type: 'link',
    content: 'Oracle Support Rewards gives customers OCI credits for support-spend optimization.',
    url: 'https://www.oracle.com/support/rewards/',
    tags: ['support', 'rewards', 'customers'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'row-4',
    parentId: 'root-6',
    title: 'Enablement working note',
    type: 'text',
    content: 'Use this table to track which public Oracle facts should appear in field decks, MyLearn modules, and portal cards.',
    tags: ['enablement', 'notes'],
    updatedAt: getPastDate(3),
  },
  {
    id: 'row-5',
    parentId: 'root-6',
    title: 'Publish AI certification path update',
    type: 'task',
    content: 'Refresh learning links for Oracle AI, Database, and OCI before the next enablement cycle.',
    completed: false,
    tags: ['action-item', 'certification', 'ai'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'root-7',
    parentId: null,
    title: 'Oracle operations analytics',
    type: 'concept',
    content: 'Analytics view fed by the portal resources that summarize Oracle program activity.',
    color: '#5b6dee',
    tags: ['dashboard', 'analytics', 'overview'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-1',
    parentId: 'root-7',
    title: 'OCI footprint fact pack',
    type: 'text',
    content: 'Include 50+ public regions, 28 countries, 200+ services, 2 sovereign regions, and 23 dedicated regions.',
    tags: ['oci', 'regions', 'data'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-2',
    parentId: 'root-7',
    title: 'AI Database launch deck',
    type: 'document',
    content: 'Reference deck placeholder for AI Database 26ai public positioning.',
    url: 'https://www.oracle.com/database/ai-database/',
    tags: ['database', 'document', 'launch'],
    updatedAt: getPastDate(2),
  },
  {
    id: 'a-3',
    parentId: 'root-7',
    title: 'Oracle events index',
    type: 'link',
    content: 'Public Oracle events page used as the source for event examples in this portal.',
    url: 'https://www.oracle.com/events/',
    tags: ['events', 'reference', 'field'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-4',
    parentId: 'root-7',
    title: 'Refresh support rewards FAQ',
    type: 'task',
    content: 'Make sure the portal references the current standard and ULA credit rates accurately.',
    completed: false,
    tags: ['support', 'planning', 'customers'],
    updatedAt: getPastDate(1),
  },
  {
    id: 'a-5',
    parentId: 'root-7',
    title: 'MyLearn path alignment',
    type: 'task',
    content: 'Cross-check learning links used by the dashboard, calendar, and portal surfaces.',
    completed: true,
    tags: ['learning', 'planning', 'enablement'],
    updatedAt: getPastDate(3),
  },
];
